IF [Sale Type] = 'WD' THEN 'Warranty Deed - Conventional'
ELSEIF [Sale Type] = 'CWD' THEN 'Warranty Deed - Cash'
ELSEIF [Sale Type] = 'VWD' THEN 'Warranty Deed - VA Loan'
ELSEIF [Sale Type] = 'New' THEN 'Home just constructed and sold'
ELSEIF [Sale Type] = 'COD' THEN 'Court Officer Deed/Estate'
ELSEIF [Sale Type] = 'Con' THEN 'Contract 15% Down payment regular terms'
ELSEIF [Sale Type] = 'ConLw' THEN 'Contract Low Down payment and low interest'
ELSEIF [Sale Type] = 'ConLI' THEN 'Contract Low Interest'
ELSEIF [Sale Type] = 'ConLD' THEN 'Contract Low Down'
ELSEIF [Sale Type] = 'Oth' THEN 'Other'
END